# Generated by Django 5.0.1 on 2024-03-21 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('published_date', models.CharField(max_length=10)),
                ('isbn', models.CharField(max_length=15)),
                ('page_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4000)])),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
