# Generated by Django 5.0.1 on 2024-05-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_id_alter_book_isbn_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='isbn',
            field=models.CharField(max_length=50),
        ),
    ]
