# Generated by Django 4.2.6 on 2024-04-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_customuser_friend_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.BigIntegerField(verbose_name=10)),
                ('rank_last_week', models.BigIntegerField(verbose_name=10)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=130)),
                ('description', models.CharField(max_length=1000)),
                ('amazon_product_url', models.CharField(max_length=100)),
            ],
        ),
    ]
