# Generated by Django 5.0.1 on 2024-05-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_book'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
