# Generated by Django 5.0.1 on 2024-05-09 19:18

import general.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friend_code',
            field=models.IntegerField(default=general.models.generate_unique_code, unique=True),
        ),
    ]
