# Generated by Django 5.0.1 on 2024-05-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default_pfp.jpg', upload_to='media/'),
        ),
    ]
