# Generated by Django 5.0.1 on 2024-05-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
