# Generated by Django 5.0.1 on 2024-05-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='badges/')),
                ('description', models.CharField(max_length=300)),
                ('target_pages', models.IntegerField()),
                ('target_books', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(blank=True, to='general.badge'),
        ),
    ]
