# Generated by Django 5.0.1 on 2024-05-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_badge_customuser_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(upload_to='static/badges/'),
        ),
    ]
