# Generated by Django 5.0.1 on 2024-05-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_alter_badge_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
    ]
