# Generated by Django 5.0.1 on 2024-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_remove_badge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image_path',
            field=models.CharField(default='badges/lockedBadge.png', max_length=100),
        ),
    ]
