# Generated by Django 5.0.1 on 2024-05-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_badge_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image_path',
        ),
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(default='badges/lockedBadge.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='badge',
            name='target_books',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='badge',
            name='target_pages',
            field=models.PositiveIntegerField(),
        ),
    ]
