# Generated by Django 5.0.1 on 2024-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_remove_badge_image_path_badge_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=36, unique=True)),
                ('last_executed', models.DateTimeField(blank=True)),
                ('last_execution_successful', models.BooleanField(default=True)),
            ],
        ),
    ]
