# Generated by Django 5.0.1 on 2024-05-13 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_scheduledtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtasks',
            name='last_executed',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
