# Generated by Django 5.0.1 on 2024-03-21 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weekly_score', models.PositiveIntegerField(default=0)),
                ('monthly_score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
